'''
This example shows how to interact with Dropbox API to restore files encrypted by a ransom.
Even if a ransom deletes original files from the file-system, dropbox still keeps old copies.
We restore the last available revision of a file.
Optionally encrypted files can be deleted with no harm (they're unrecoverable anyway).
'''

import dropbox
import sys
import re

files = []
has_more = True

def gather_elements(folderList):
    for entry in folderList.entries:
        # rap here is the extension of ransom' encrypted file
        if re.search('.rap$', entry.name):
            files.append(entry.path_lower)

# Here goes the token generated by your dropbox app
TOKEN = ''
dbx = dropbox.Dropbox(TOKEN)
dbx.users_get_current_account()
folderList = dbx.files_list_folder('', recursive=True)

while has_more:
    gather_elements(folderList)
    if folderList.has_more:
        folderList = dbx.files_list_folder_continue(folderList.cursor)
    else:
        has_more = False

# Examine all the files encrypted by the ransom
for f in files:
    try:
        # Check that it is still marked as deleted
        fileName = f.replace('.rap', '')
        # Take the version of the file before being encrypted
        last_revision = dbx.files_list_revisions(fileName,
                        mode=dropbox.files.ListRevisionsMode('path', None), limit=1)
        # If not there yet, let's restore it
        if last_revision.is_deleted is True:
            print('Restoring {} with revision {} ...'.format(fileName,
                    last_revision.entries[0].rev))
            dbx.files_restore(fileName, last_revision.entries[0].rev)
        else:
            # If it was already restored somehow, keep it untouched
            print('File {} was already in place, no action performed'.format(fileName))
            continue
    except Exception as ex:
        print(ex)
        continue
sys.exit(0)

# To delete files, comment previous call to sys.exit(0)
for f in files:
    try:
        print("Finally deleting {}".format(f))
        dbx.files_delete(f)
    except Exception as ex:
        print(ex)
sys.exit(0)
